### PR TITLE
Enable social cards and add Netlify build cache

### PR DESCRIPTION
**Pull request by squidfunk**
This PR enables [social cards](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/). Additionally, I've added a plugin which caches the generated social cards when building via Netlify, as image processing takes some time. I haven't used Netlify's build caching before, so let's see how that works out.

__Example__:

7aab82a6c129e1af1dec3d53cc37c36c

__Build time__:

- 1st run: 40s
- 2nd+ run (with cache): 22s

### CODE REVIEW

**Review by mifeng — CHANGES_REQUESTED** [review]
Screen Shot 2022-01-20 at 7 06 07 PM

I tried the Deploy Preview in the Twitter card validator but the card doesn't seem to appear.  However, everything else looks fine. I invited you to our Netlify org so that you can take a look.

**Comment by squidfunk** [comment]
@mifeng I should have noted that this is not expected to work with the deploy previews, because social card images must be absolute URLs, which means `site_url` is used to compute the URL for the image. Since the `site_url` is set to https://hummingbot.org, Twitter's card validator doesn't see a matching URL for the social image:

Bildschirmfoto 2022-01-21 um 09 10 45
 
If you want to preview it, I can change the`site_url` to the Netlify deploy preview URL temporarily, which will make it work, but we will need to change it back before. If I replace the domain part in the screenshot above, the image shows correctly:
https://deploy-preview-22--hummingbot-foundation-site.netlify.app/assets/images/social/index.png

**Review by mifeng — APPROVED** [review]
Makes sense! LGTM

**Comment by squidfunk** [comment]
Looking good:

Bildschirmfoto 2022-01-21 um 16 25 48

**Pull request merged**
