### PR TITLE
(doc) add btc markets connector documentation

### PR DESCRIPTION
**Pull request by vdmerweandre**

### CODE REVIEW

**Comment by vdmerweandre** [comment]
Hi @JeremyKono , who can I get to help review and possibly merge this PR? 
It will be good to have this as part of Release 1.10 since it give further info on the new btc markets connector that is going in. 
Thx

**Comment by JeremyKono** [comment]
Hi @vdmerweandre it won't be merged in until the release since the connector is still in `development` and not in master

**Comment by vdmerweandre** [comment]
Thank you @JeremyKono .

**Comment by mifeng** [comment]
Added to https://github.com/hummingbot/hummingbot-site/pull/151

**Pull request closed without merging**
